# -*- coding: utf-8 -*-
"""Multiple-Template-Matching

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ki05fK7Ew0mYL_fIo9K5ncqWYBLIJ1TK
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img_rgb = cv2.imread('image1.png')
img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)
template = cv2.imread('image2.png',0)
w, h = template.shape[::-1]

res = cv2.matchTemplate(img_gray,template,cv2.TM_CCOEFF_NORMED)
threshold = 0.8
loc = np.where( res >= threshold)
for pt in zip(*loc[::-1]):
    cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (0,0,255), 2)

cv2.imwrite('res.png',img_rgb)